let favoriteMovie: string = "John Wick";
let firstName = "Waleed";
let lastName = "Arshad";
let age: number = 32;
console.log(`HI, this is ${firstName} and i am ${age} years old`);
const currentmood_Angry: boolean = true;
console.log(`Full Name: ${firstName} ${lastName}`);
let productName: string = "Mobile";
let productPrice: number = 150.99;
console.log(`Product: ${productName}, Price: $${productPrice}`);
let numberOfPets: number = 1;
let isBirthday: boolean = false;
let userInfo: string = `First Name: ${firstName}, Last Name: ${lastName}, Age: ${age}`;
console.log(userInfo);
const birthYear: number = 1992;
console.log(birthYear);
let city: string = "Lahore";
let country: string = "Pakistan";
let fullAddress: string = `${city}, ${country}`;
console.log(fullAddress);
let todaysTemperature: number = 26;
console.log(todaysTemperature);
