"use strict";
let favoriteMovie = "John Wick";
let firstName = "Waleed";
let lastName = "Arshad";
let age = 32;
console.log(`HI, this is ${firstName} and i am ${age} years old`);
const currentmood_Angry = true;
console.log(`Full Name: ${firstName} ${lastName}`);
let productName = "Mobile";
let productPrice = 150.99;
console.log(`Product: ${productName}, Price: $${productPrice}`);
let numberOfPets = 1;
let isBirthday = false;
let userInfo = `First Name: ${firstName}, Last Name: ${lastName}, Age: ${age}`;
console.log(userInfo);
const birthYear = 1992;
console.log(birthYear);
let city = "Lahore";
let country = "Pakistan";
let fullAddress = `${city}, ${country}`;
console.log(fullAddress);
let todaysTemperature = 26;
console.log(todaysTemperature);
